# Setup
title: PAGE TITLE
url: SITE URL
paginate: 1
baseurl: "" # LEAVE EMPTY, unless different site for files
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: AUTHOR
  url:
  email:

# Custom vars
version: 1.0.0

# Navbar page list
# Add things here to add them to navigation bar at top
nav:
  - title: About
    url: /about
